#!/usr/bin/env python3
"""
cheap-cam-portal — Windows command-line tool.

All Windows .bat files in this folder are thin wrappers around this script.
Subcommands:

  setup                  one-time install: download mediamtx + ffmpeg,
                         prompt for cam config, write .env, render
                         mediamtx.yml, start services, open browser

  start                  launch mediamtx + portal in the background
  stop                   kill them
  regen                  rebuild mediamtx.yml from .env

  install-autostart      create a Startup-folder shortcut so the portal
                         launches every time you log into Windows
  uninstall-autostart    remove that shortcut

Run any subcommand with --help for details.
"""

from __future__ import annotations
import argparse
import io
import os
import re
import shlex
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

# ---------- locations ----------
HERE = Path(__file__).resolve().parent                # cheap-cam-portal\windows
PROJECT = HERE.parent                                 # cheap-cam-portal
BIN = HERE / "bin"                                    # cheap-cam-portal\windows\bin
PORTAL = PROJECT / "portal"
ENV_FILE = PROJECT / ".env"
ENV_EXAMPLE = PROJECT / ".env.example"
TEMPLATE_YML = PROJECT / "mediamtx.template.yml"
RENDERED_YML = PROJECT / "mediamtx.yml"
LOGS = PROJECT / "logs"

MEDIAMTX_EXE = BIN / "mediamtx.exe"
FFMPEG_EXE = BIN / "ffmpeg.exe"
FFPROBE_EXE = BIN / "ffprobe.exe"

MEDIAMTX_PID = PROJECT / ".mediamtx.pid"
PORTAL_PID = PROJECT / ".portal.pid"

# ---------- download targets ----------
# pin versions for reproducibility — bump intentionally if you upgrade
MEDIAMTX_VERSION = "v1.18.2"
MEDIAMTX_ZIP_URL = (
    f"https://github.com/bluenviron/mediamtx/releases/download/"
    f"{MEDIAMTX_VERSION}/mediamtx_{MEDIAMTX_VERSION}_windows_amd64.zip"
)

# BtbN releases — `latest` is auto-bumped, no version pin available there.
# We pick the "essentials" gpl build which has ffmpeg.exe + ffprobe.exe.
FFMPEG_ZIP_URL = (
    "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/"
    "ffmpeg-master-latest-win64-gpl.zip"
)

# ---------- colors (best effort on Windows 10+ with VT enabled) ----------
def _enable_vt():
    if os.name == "nt":
        try:
            import ctypes
            kernel32 = ctypes.windll.kernel32
            handle = kernel32.GetStdHandle(-11)
            mode = ctypes.c_uint32()
            if kernel32.GetConsoleMode(handle, ctypes.byref(mode)):
                kernel32.SetConsoleMode(handle, mode.value | 0x0004)
        except Exception:
            pass

_enable_vt()

def _c(code):
    return f"\033[{code}m" if sys.stdout.isatty() else ""

GREEN = _c("1;32"); RED = _c("1;31"); YELLOW = _c("1;33")
BLUE  = _c("1;34"); DIM = _c("2");   RESET = _c("0")

def step(msg):  print(f"{BLUE}==>{RESET} {msg}")
def ok(msg):    print(f"{GREEN}ok{RESET}  {msg}")
def warn(msg):  print(f"{YELLOW}!!{RESET}  {msg}")
def err(msg):   print(f"{RED}xx{RESET}  {msg}", file=sys.stderr)
def info(msg):  print(f"{DIM}--{RESET}  {msg}")

# ---------- env file ----------
def load_env() -> dict[str, str]:
    out: dict[str, str] = {}
    if not ENV_FILE.exists():
        return out
    for raw in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out

def write_env(d: dict[str, str]) -> None:
    lines = [
        "# generated by windows\\cli.py setup",
        f"# at {time.strftime('%Y-%m-%d %H:%M:%S')}",
    ]
    for k, v in d.items():
        lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

# ---------- downloads ----------
def _download(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    info(f"GET {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "cheap-cam-portal-setup"})
    with urllib.request.urlopen(req, timeout=60) as resp, open(dest, "wb") as f:
        total = int(resp.headers.get("Content-Length") or 0)
        chunk = 1 << 16
        read = 0
        last = 0.0
        while True:
            buf = resp.read(chunk)
            if not buf:
                break
            f.write(buf)
            read += len(buf)
            now = time.time()
            if total and now - last > 0.2:
                pct = read * 100 // total
                mb = read / (1024 * 1024)
                tmb = total / (1024 * 1024)
                sys.stdout.write(f"\r    {mb:6.1f} / {tmb:6.1f} MB  ({pct}%)")
                sys.stdout.flush()
                last = now
        if total:
            sys.stdout.write("\n")
            sys.stdout.flush()

def _extract_first(zip_path: Path, names: list[str], dest_dir: Path) -> None:
    """Extract the first file in `names` (matched by suffix) from the zip
    into dest_dir, flattening any internal directory structure."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path) as zf:
        members = zf.namelist()
        for want in names:
            hit = next((m for m in members if m.lower().endswith("/" + want.lower())
                        or m.lower() == want.lower()), None)
            if not hit:
                continue
            with zf.open(hit) as src, open(dest_dir / want, "wb") as dst:
                shutil.copyfileobj(src, dst)
            info(f"extracted {want}")

def ensure_mediamtx() -> None:
    if MEDIAMTX_EXE.exists():
        ok(f"mediamtx.exe already in {BIN}")
        return
    step("Downloading MediaMTX")
    tmp = BIN / "_mediamtx.zip"
    _download(MEDIAMTX_ZIP_URL, tmp)
    _extract_first(tmp, ["mediamtx.exe"], BIN)
    tmp.unlink(missing_ok=True)
    if not MEDIAMTX_EXE.exists():
        raise SystemExit("mediamtx.exe extraction failed")
    ok(str(MEDIAMTX_EXE))

def ensure_ffmpeg() -> None:
    if FFMPEG_EXE.exists() and FFPROBE_EXE.exists():
        ok(f"ffmpeg.exe already in {BIN}")
        return
    step("Downloading FFmpeg (~80 MB)")
    tmp = BIN / "_ffmpeg.zip"
    _download(FFMPEG_ZIP_URL, tmp)
    _extract_first(tmp, ["ffmpeg.exe", "ffprobe.exe"], BIN)
    tmp.unlink(missing_ok=True)
    if not FFMPEG_EXE.exists():
        raise SystemExit("ffmpeg.exe extraction failed")
    ok(str(FFMPEG_EXE))

# ---------- mediamtx.yml render ----------
def regen_yml() -> None:
    env = load_env()
    if not env:
        raise SystemExit("No .env yet — run `windows\\setup.bat` first.")
    tpl = TEMPLATE_YML.read_text(encoding="utf-8")
    mapping = {
        "CAM_IP":      env.get("CAM_IP", "192.168.0.21"),
        "CAM_USER":    env.get("CAM_USER", "super"),
        "CAM_PASS":    env.get("CAM_PASS", "fullhansuper"),
        "CAM_PORT":    env.get("CAM_PORT", "8554"),
        "CAM_PATH":    env.get("CAM_PATH", "stream1"),
        "WEBRTC_PORT": env.get("WEBRTC_PORT", "8889"),
    }
    for k, v in mapping.items():
        tpl = tpl.replace("{{" + k + "}}", v)
    RENDERED_YML.write_text(tpl, encoding="utf-8")
    ok(f"wrote {RENDERED_YML}")

# ---------- process helpers ----------
DETACHED_PROCESS = 0x00000008
CREATE_NEW_PROCESS_GROUP = 0x00000200
CREATE_NO_WINDOW = 0x08000000

def _spawn(cmd: list[str], log_path: Path, cwd: Path) -> int:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    f = open(log_path, "ab")
    flags = 0
    if os.name == "nt":
        flags = DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW
    proc = subprocess.Popen(
        cmd,
        cwd=str(cwd),
        stdout=f,
        stderr=subprocess.STDOUT,
        stdin=subprocess.DEVNULL,
        close_fds=True,
        creationflags=flags if os.name == "nt" else 0,
    )
    return proc.pid

def _alive(pid: int) -> bool:
    if os.name == "nt":
        # tasklist with /FI; if not present, the output begins with "INFO:"
        try:
            r = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}", "/NH"],
                capture_output=True, text=True, timeout=4,
            )
            return f" {pid} " in r.stdout
        except Exception:
            return False
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False

def _kill(pid: int) -> bool:
    if not _alive(pid):
        return False
    if os.name == "nt":
        subprocess.run(["taskkill", "/PID", str(pid), "/T", "/F"],
                       capture_output=True)
        return True
    try:
        os.kill(pid, 15)
        return True
    except OSError:
        return False

def _kill_by_name(image: str) -> int:
    if os.name != "nt":
        return 0
    r = subprocess.run(["taskkill", "/IM", image, "/T", "/F"],
                       capture_output=True, text=True)
    return 0 if "SUCCESS" not in r.stdout else 1

# ---------- subcommands ----------
def cmd_setup(_args) -> int:
    print(GREEN + "== cheap-cam-portal — Windows setup ==" + RESET)

    # 1. dependencies (mediamtx + ffmpeg) — Python is required and already running.
    step("Ensuring dependencies in windows\\bin\\")
    ensure_mediamtx()
    ensure_ffmpeg()

    # 2. .env
    step("Configuring camera")
    if ENV_FILE.exists():
        ok(".env already present (delete it to be re-prompted)")
    else:
        print()
        print("I need a few things about your camera. Press Enter to accept each [default].")
        print()

        def ask(prompt, default):
            try:
                got = input(f"  {prompt} [{default}]: ").strip()
            except (EOFError, KeyboardInterrupt):
                print(); return default
            return got or default

        cam_ip   = ask("Cam IP address               ", "192.168.0.21")
        cam_user = ask("Cam RTSP username            ", "super")
        cam_pass = ask("Cam RTSP password            ", "fullhansuper")
        cam_port = ask("Cam RTSP port                ", "8554")
        cam_path = ask("Cam stream path              ", "stream1")
        write_env({
            "CAM_IP": cam_ip,
            "CAM_USER": cam_user,
            "CAM_PASS": cam_pass,
            "CAM_PORT": cam_port,
            "CAM_PATH": cam_path,
            "HTTP_PORT": "8888",
            "WEBRTC_PORT": "8889",
            # Windows default media folders
            "MOVIES_DIR": "~/Videos/cam-portal",
            "SHOTS_DIR":  "~/Pictures/cam-portal",
        })
        ok(".env written")

    # 3. connectivity
    step("Pinging cam")
    env = load_env()
    cam_ip = env.get("CAM_IP", "192.168.0.21")
    ping_cmd = ["ping", "-n", "1", "-w", "1000", cam_ip] if os.name == "nt" \
               else ["ping", "-c", "1", "-W", "1000", cam_ip]
    r = subprocess.run(ping_cmd, capture_output=True)
    if r.returncode == 0:
        ok(f"{cam_ip} responds")
    else:
        warn(f"{cam_ip} not responding — check Wi-Fi and CAM_IP in .env. "
             f"The portal will keep retrying once started.")

    # 4. mediamtx.yml
    step("Generating mediamtx.yml from template")
    regen_yml()

    # 5. start
    step("Starting services")
    cmd_start(None)

    # 6. open browser
    step("Opening browser")
    time.sleep(1)
    http_port = env.get("HTTP_PORT", "8888")
    try:
        if os.name == "nt":
            os.startfile(f"http://127.0.0.1:{http_port}/")  # noqa: T201
        else:
            subprocess.run(["open", f"http://127.0.0.1:{http_port}/"])
    except Exception as e:
        warn(f"couldn't auto-open browser: {e}")

    print()
    print(GREEN + "All set." + RESET)
    print(f"  Portal:   http://127.0.0.1:{http_port}/")
    print(f"  Movies:   { _expand(env.get('MOVIES_DIR', '~/Videos/cam-portal')) }")
    print(f"  Shots:    { _expand(env.get('SHOTS_DIR',  '~/Pictures/cam-portal')) }")
    print()
    print("  Stop:                  windows\\stop.bat")
    print("  Start:                 windows\\start.bat")
    print("  Auto-start at login:   windows\\install-autostart.bat   (optional)")
    print("  Change cam settings:   delete .env then re-run setup.bat")
    return 0

def _expand(p: str) -> str:
    return os.path.expanduser(p)

def cmd_start(_args) -> int:
    # generated config required
    if not RENDERED_YML.exists():
        err("mediamtx.yml missing — run setup first.")
        return 1
    if not MEDIAMTX_EXE.exists():
        err(f"mediamtx.exe missing — expected at {MEDIAMTX_EXE}. Re-run setup.")
        return 1

    # tear down any prior run
    cmd_stop(None, quiet=True)

    env = load_env()
    LOGS.mkdir(exist_ok=True)

    # Pick a Python interpreter to run the portal under.
    py = _python_bin()

    # Make ffmpeg/ffprobe in windows\bin findable by the portal's subprocess calls.
    portal_env = os.environ.copy()
    portal_env["PATH"] = str(BIN) + os.pathsep + portal_env.get("PATH", "")

    # Start MediaMTX
    pid_m = _spawn(
        [str(MEDIAMTX_EXE), str(RENDERED_YML)],
        LOGS / "mediamtx.log",
        cwd=PROJECT,
    )
    MEDIAMTX_PID.write_text(str(pid_m))
    time.sleep(1.0)
    if not _alive(pid_m):
        err("mediamtx crashed at start. See logs\\mediamtx.log")
        return 1

    # Start portal — spawn-detached, with PATH pointing at our bin\ for ffmpeg
    pid_p = _spawn_with_env(
        [py, str(PORTAL / "portal.py")],
        LOGS / "portal.log",
        cwd=PROJECT,
        env=portal_env,
    )
    PORTAL_PID.write_text(str(pid_p))
    time.sleep(1.0)
    if not _alive(pid_p):
        err("portal crashed at start. See logs\\portal.log")
        return 1

    print(f"Started:")
    print(f"  mediamtx pid: {pid_m}   (log: logs\\mediamtx.log)")
    print(f"  portal pid:   {pid_p}   (log: logs\\portal.log)")
    http_port = env.get("HTTP_PORT", "8888")
    print(f"  open:         http://127.0.0.1:{http_port}/")
    return 0

def _spawn_with_env(cmd, log_path, cwd, env):
    """Same as _spawn but passes a custom env dict to the child."""
    log_path.parent.mkdir(parents=True, exist_ok=True)
    f = open(log_path, "ab")
    flags = 0
    if os.name == "nt":
        flags = DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW
    proc = subprocess.Popen(
        cmd, cwd=str(cwd), env=env,
        stdout=f, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL,
        close_fds=True,
        creationflags=flags if os.name == "nt" else 0,
    )
    return proc.pid

def cmd_stop(_args, quiet: bool = False) -> int:
    killed = 0
    for label, pidfile in (("mediamtx", MEDIAMTX_PID), ("portal", PORTAL_PID)):
        if pidfile.exists():
            try:
                pid = int(pidfile.read_text().strip())
                if _kill(pid):
                    killed += 1
                    if not quiet:
                        ok(f"stopped {label} (pid {pid})")
            except Exception:
                pass
            pidfile.unlink(missing_ok=True)
    # also kill orphans by image name (only catches our exact exe)
    if os.name == "nt":
        # mediamtx.exe is unambiguous — safe.
        subprocess.run(["taskkill", "/IM", "mediamtx.exe", "/T", "/F"],
                       capture_output=True)
        # python.exe is NOT unique to us, so don't kill by name.
    if not quiet and killed == 0:
        info("nothing was running")
    return 0

def cmd_regen(_args) -> int:
    regen_yml()
    return 0

# ---------- auto-start ----------
def _startup_lnk_path() -> Path:
    base = Path(os.path.expandvars(r"%APPDATA%"))
    return base / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup" \
                / "cheap-cam-portal.lnk"

def cmd_install_autostart(_args) -> int:
    if os.name != "nt":
        err("install-autostart is Windows-only")
        return 1
    target = HERE / "start.bat"
    if not target.exists():
        err(f"missing {target}")
        return 1
    lnk = _startup_lnk_path()
    # Escape single quotes for PowerShell single-quoted strings (' -> '').
    def psq(p):
        return str(p).replace("'", "''")
    # Build the shortcut with PowerShell + WScript.Shell COM (works on every Win10+).
    ps = (
        "$ws = New-Object -ComObject WScript.Shell;"
        f"$s = $ws.CreateShortcut('{psq(lnk)}');"
        f"$s.TargetPath = '{psq(target)}';"
        f"$s.WorkingDirectory = '{psq(PROJECT)}';"
        "$s.WindowStyle = 7;"     # 7 = minimized
        "$s.IconLocation = 'imageres.dll,15';"
        "$s.Save();"
    )
    lnk.parent.mkdir(parents=True, exist_ok=True)
    r = subprocess.run(
        ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        err(f"powershell failed: {r.stderr.strip()}")
        return 1
    ok(f"installed shortcut: {lnk}")
    print("It will run at every login and start the portal in the background.")
    print("Open: http://127.0.0.1:8888/")
    print("Remove with: windows\\uninstall-autostart.bat")
    return 0

def cmd_uninstall_autostart(_args) -> int:
    if os.name != "nt":
        err("uninstall-autostart is Windows-only")
        return 1
    lnk = _startup_lnk_path()
    if lnk.exists():
        lnk.unlink()
        ok(f"removed {lnk}")
    else:
        info(f"no shortcut at {lnk}")
    print("Auto-start disabled. The portal will not restart on next login.")
    print("(Run windows\\stop.bat if you also want to stop the currently running services.)")
    return 0

# ---------- python locator ----------
def _python_bin() -> str:
    # We're running under a Python already; reuse it.
    return sys.executable

# ---------- main ----------
def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="cli.py", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("setup",                help="one-time install + start")
    sub.add_parser("start",                help="launch services")
    sub.add_parser("stop",                 help="kill services")
    sub.add_parser("regen",                help="rebuild mediamtx.yml from .env")
    sub.add_parser("install-autostart",    help="add startup shortcut")
    sub.add_parser("uninstall-autostart",  help="remove startup shortcut")
    args = p.parse_args(argv)

    dispatch = {
        "setup":               cmd_setup,
        "start":               cmd_start,
        "stop":                cmd_stop,
        "regen":               cmd_regen,
        "install-autostart":   cmd_install_autostart,
        "uninstall-autostart": cmd_uninstall_autostart,
    }
    return dispatch[args.cmd](args) or 0

if __name__ == "__main__":
    sys.exit(main())
