#!/usr/bin/env bash
# cheap-cam-portal — one-time setup.
# Installs MediaMTX + ffmpeg, prompts for cam config, generates configs, starts services.
# Re-run any time to refresh dependencies or regenerate mediamtx.yml from .env.

set -e
cd "$(dirname "$0")"

# ---------- pretty colors ----------
if [[ -t 1 ]]; then
  G='\033[1;32m'; R='\033[1;31m'; Y='\033[1;33m'; B='\033[1;34m'; D='\033[2m'; N='\033[0m'
else
  G=''; R=''; Y=''; B=''; D=''; N=''
fi

step()  { printf "${B}==>${N} %s\n" "$1"; }
warn()  { printf "${Y}!! ${N}%s\n" "$1"; }
fail()  { printf "${R}xx ${N}%s\n" "$1" >&2; }
ok()    { printf "${G}ok${N} %s\n" "$1"; }

cat <<'BANNER'
        _                                                                  _        _
   ___ | |__   ___  __ _ _ __   ___ __ _ _ __ ___    _ __   ___  _ __ ___| |_ __ _| |
  / __|| '_ \ / _ \/ _` | '_ \ / __/ _` | '_ ` _ \  | '_ \ / _ \| '__/ __| __/ _` | |
 | (__ | | | |  __/ (_| | |_) | (_| (_| | | | | | | | |_) | (_) | |  \__ \ || (_| | |
  \___||_| |_|\___|\__,_| .__/ \___\__,_|_| |_| |_| | .__/ \___/|_|  |___/\__\__,_|_|
                        |_|                         |_|

BANNER

# ---------- step 1: Homebrew ----------
step "Checking for Homebrew"
if ! command -v brew >/dev/null 2>&1; then
  fail "Homebrew not found."
  cat <<EOF

  Homebrew is how macOS users install developer tools.
  Install it by copying this command, pasting into Terminal, and pressing Enter:

    /bin/bash -c "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  When it finishes, re-run this script:

    cd "$(pwd)" && ./setup.sh

EOF
  exit 1
fi
ok "$(brew --version | head -1)"

# ---------- step 2: dependencies ----------
step "Checking dependencies (mediamtx, ffmpeg, python3)"
need_install=()
for pkg in mediamtx ffmpeg python@3.13; do
  short=${pkg##*/}; short=${short%%@*}
  if brew list "$pkg" >/dev/null 2>&1 || brew list "$short" >/dev/null 2>&1; then
    ok "$short already installed"
  else
    need_install+=("$pkg")
  fi
done
if [[ ${#need_install[@]} -gt 0 ]]; then
  warn "Installing: ${need_install[*]}"
  brew install "${need_install[@]}"
fi

# ---------- step 3: .env ----------
step "Configuring camera"
if [[ -f .env ]]; then
  ok ".env already present (edit it manually to change cam settings, then re-run ./setup.sh)"
else
  echo
  echo "I need a few things about your camera. Press Enter to accept each [default]."
  echo
  read -r -p "Cam IP address               [192.168.0.21]: " CAM_IP
  read -r -p "Cam RTSP username                  [super]: " CAM_USER
  read -r -p "Cam RTSP password           [fullhansuper]: " CAM_PASS
  read -r -p "Cam RTSP port                       [8554]: " CAM_PORT
  read -r -p "Cam stream path                  [stream1]: " CAM_PATH

  CAM_IP=${CAM_IP:-192.168.0.21}
  CAM_USER=${CAM_USER:-super}
  CAM_PASS=${CAM_PASS:-fullhansuper}
  CAM_PORT=${CAM_PORT:-8554}
  CAM_PATH=${CAM_PATH:-stream1}

  cat > .env <<EOF
# generated by setup.sh on $(date)
CAM_IP=$CAM_IP
CAM_USER=$CAM_USER
CAM_PASS=$CAM_PASS
CAM_PORT=$CAM_PORT
CAM_PATH=$CAM_PATH
HTTP_PORT=8888
WEBRTC_PORT=8889
MOVIES_DIR=~/Movies/cam-portal
SHOTS_DIR=~/Pictures/cam-portal
EOF
  ok ".env written"
fi

# ---------- step 4: connectivity check ----------
step "Pinging cam"
# shellcheck disable=SC1091
set -a; source .env; set +a
if ping -c 1 -W 1000 "$CAM_IP" >/dev/null 2>&1; then
  ok "$CAM_IP responds"
else
  warn "$CAM_IP not responding. The portal will keep retrying once you start it,"
  warn "but check: (a) cam is powered, (b) cam is on the same WiFi as your Mac,"
  warn "(c) CAM_IP in .env matches what the cam actually has."
fi

# ---------- step 5: render mediamtx.yml ----------
step "Generating mediamtx.yml from template"
./regen-config.sh

# ---------- step 6: start ----------
step "Starting services"
./start.sh

# ---------- step 7: open browser ----------
step "Opening browser"
sleep 1
open "http://127.0.0.1:${HTTP_PORT:-8888}/" 2>/dev/null || true

cat <<EOF

${G}All set.${N}

  Portal:   http://127.0.0.1:${HTTP_PORT:-8888}/
  Movies:   ${MOVIES_DIR/#\~/$HOME}
  Shots:    ${SHOTS_DIR/#\~/$HOME}

  Stop services:        ./stop.sh
  Start services:       ./start.sh
  Auto-start at login:  ./install-autostart.sh   (optional)
  Change cam settings:  edit .env, then ./setup.sh again

EOF
